# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c910799148bfb73a6269bf244d3f9ace90837e670dda86d697207af592b04bc9a43de64d8b7ea113883aaf3cdef8ad2dd30cc10339376d2f893e37d38c0581ce

test:
  secret_key_base: 2a66b4a032d598c85d5f4a852c44c354dcd6ee4f70ce171bbd40de07e8f69ac72ce323b47a68559a4de734893f3ade46e4eaba774d5e34c2f61cee2cd5b7938d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
